import os
from pathlib import Path

ABS_ROOT_PATH = str(Path(__file__).parent.parent.absolute())


ASSETS_VERSION = "2023_09_23"
HD_BASE_VERSION = "2023_09_23"

ASSETS_VERSION_PATH = Path(ASSETS_VERSION)
OBJATHOR_ASSETS_DIR = ASSETS_VERSION_PATH / "assets"
OBJATHOR_FEATURES_DIR = ASSETS_VERSION_PATH / "features"
OBJATHOR_ANNOTATIONS_PATH = ASSETS_VERSION_PATH / "annotations.json.gz"

HOLODECK_BASE_DATA_DIR = Path("holodeck") / HD_BASE_VERSION

HOLODECK_THOR_FEATURES_DIR = HOLODECK_BASE_DATA_DIR / "thor_object_data"
HOLODECK_THOR_ANNOTATIONS_PATH =  HOLODECK_THOR_FEATURES_DIR / "annotations.json.gz"
HOLODECK_MATERIALS_DIR = HOLODECK_BASE_DATA_DIR / "materials"

NORMALIZED_ANNOTATIONS_PATH = Path("annotations_normalized.json.gz")
